%% ******************************* STEP 06 ********************************
% Calculate the degree of mismatch (rdc chi-2 statistic) between the crater
% orientation probability distribution function of each constant-obliquity
% simulation (0-90°) and the crater orientation probability distribution
% function as determined from the actually observed craters. Then determine
% the constant obliquity with the lowest mismatch.
%                                                            James Hu, 2022
% *************************************************************************

e_crit = 1.1;
num_inst = 1000;  % Number of instances of inter-analyst perturbation

% 1. Load the appropriate crater data and latitude-normalized obliquity
%    predictions.
scenario = 2;  % 1 = constant obliquity;
               % 2 = Gaussian variation around mean obliquity
if scenario == 2
    sigma = 5.0326;  % Standard deviation from Laskar 2004, past 2.5 Ma:
                     % load('laskar/laskar_nonchaotic.mat')
                     % rad2deg(std(laskar(1:2501,2)))
end

for mode = 1:2  % 1 = lAv; 2 = AHv
    if mode == 1
        load(sprintf('craters_obs/lAv%.2f.mat',e_crit))
        load(sprintf('iaerr_perts/lAv%.2f_pert%d.mat',e_crit,num_inst))
        load(sprintf('forward_model/obpreds4_norm_lAv%.2f.mat',e_crit),...
                     'orientationdata')
    elseif mode == 2
        load(sprintf('craters_obs/AHv%.2f.mat',e_crit))
        load(sprintf('iaerr_perts/AHv%.2f_pert%d.mat',e_crit,num_inst))
        load(sprintf('forward_model/obpreds4_norm_AHv%.2f.mat',e_crit),...
                     'orientationdata')
    end
    
    cratdata = a(:,2);
    clear a
    
% 2. Take the actual crater orientations and construct crude
%    probability distribution function (histogram)
    bin_centers = 5:10:85;
    num_bins = width(bin_centers);
    [N,X] = hist(cratdata,bin_centers);  % Raw frequencies    
    [N_p,X_p] = hist(cratdata_p,bin_centers);  % Perturbed

    num_crats = height(cratdata);
    N_norm = N / num_crats / num_bins;  % Normalized distribution
    
    N_norm_p = N_p / num_crats / num_bins;  % Perturbed
    N_norm_p_median = median(N_norm_p,2);

%% Compare the PDFs of the actual and simulated crater orientations
    
% 3. Calculate the standard error on the actual crater probability
%    distribution function; plot with error bars
    fig1 = figure('color',[1 1 1]);
    
    subplot(2,1,mode)
    hold on
    
    for i = 1:1000
        patchline(X_p,N_norm_p(:,i),'edgecolor','#74C1E4','linewidth',5,...
                  'edgealpha',0.01)  % (3)Blue
    end

    E = sqrt(N) / num_crats / num_bins;
    errorbar(X,N_norm,E,'Color','#8D6135','LineWidth',1.5)  % (1)Brown
    plot(X_p,N_norm_p_median,'Color','#74C1E4','LineWidth',1.5)

% 4. Take the simulated crater orientation data and construct crude
%    probability distribution functions; plot
    sims = zeros(91,num_bins);
    num_simcrats = height(orientationdata);
    
    for i = 0:1:90  % Loop through all obliquity scenarios
        if scenario == 1
            odata = orientationdata(:,i+1);
        elseif scenario == 2
            odata = hu_06b_gaussamp(orientationdata,i,sigma);
        end
        
        f = hist(odata,bin_centers) / num_simcrats / num_bins;
        sims(i+1,:) = f;
        
        if ismember(i,15:15:75)  % But only plot 15,30,45,60,75
            plot(bin_centers,f,'LineWidth',0.75,'LineStyle','--');
        end
    end
    
    
%% Conduct 91 chi-squared tests to determine best-match constant obliquity

% 5. Calculate reduced chi-squared values for each obliquity
    chi2_sims = hu_06a_chi2test(sims'*num_crats*num_bins,N');
    chi2_sims_p = zeros(91,1000);

    for i = 1:1000
        chi2_sims_p(:,i) = hu_06a_chi2test(sims'*num_crats*num_bins,...
                                          N_p(:,i)');
    end
    
    chi2_sims_rdc = chi2_sims / (num_bins-1);
    chi2_sims_rdc_p = chi2_sims_p / (num_bins-1);
    chi2_sims_rdc_p_median = median(chi2_sims_rdc_p,2);

    %% 6. Plot
    fig2 = figure('color',[1 1 1]);
    hold on
    ylim([0 25])
    
    for i = 1:1000
        patchline(0:90,chi2_sims_rdc_p(:,i),'edgecolor','#74C1E4',...
                  'linewidth',5,'edgealpha',0.01)
    end

    plot(0:90,chi2_sims_rdc,'LineWidth',1.5,'Color','#8D6135')

    plot(0:90,chi2_sims_rdc_p_median,'LineWidth',1.5,'Color','#74C1E4')
    [~,chi2_sims_rdc_p_mins] = min(chi2_sims_rdc_p);
    chi2_sims_rdc_p_mins = chi2_sims_rdc_p_mins - 1;

    % Code for Fig 3.3 (ingested by hu05_plot_age_obliquity.m)
    if mode == 1
        fname = sprintf('iaerr_perts/chi2_sims_rdc_p_mins_lAv%.2f',e_crit);
    elseif mode == 2
        fname = sprintf('iaerr_perts/chi2_sims_rdc_p_mins_AHv%.2f',e_crit);
    end
    
    save(fname,'chi2_sims_rdc_p_mins')

    % 7. Draw lines on plot
    [yMin_rdc,xIndex_rdc] = min(chi2_sims_rdc);  % Observed
    xline(xIndex_rdc-1,'Color','#8D6135','LineStyle','-','LineWidth',0.75)
    y_uncert_rdc = yMin_rdc + sqrt(2*(num_bins-1))/(num_bins-1);
    yline(y_uncert_rdc,'Color','#8D6135','LineStyle','--','LineWidth',0.75)
    y_uncert_rdc_arr = y_uncert_rdc + zeros(1,91);
    [xIndex_uncert_rdc,~] = intersections(0:90,chi2_sims_rdc,0:90,...
                                          y_uncert_rdc_arr);
    xline([min(xIndex_uncert_rdc) max(xIndex_uncert_rdc)],'Color',...
          '#8D6135','LineStyle','--','LineWidth',0.75)  % Uncertainty (x)
    
    [yMin_rdc_p,xIndex_rdc_p] = min(chi2_sims_rdc_p_median);  % Perturbed
    xline(xIndex_rdc_p-1,'Color','#74C1E4','LineStyle','-','LineWidth',...
          0.75)
      
    y_uncert_rdc_p = yMin_rdc_p + sqrt(2*(num_bins-1))/(num_bins-1);
    yline(y_uncert_rdc_p,'Color','#74C1E4','LineStyle','--','LineWidth',...
          0.75)
    y_uncert_rdc_arr_p = y_uncert_rdc_p + zeros(1,91);
    [xIndex_uncert_rdc_p,~] = intersections(0:90,chi2_sims_rdc_p_median,...
                                            0:90,y_uncert_rdc_arr_p);
    xline([min(xIndex_uncert_rdc_p) max(xIndex_uncert_rdc_p)],'Color',...
          '#74C1E4','LineStyle','--','LineWidth',0.75)  % Uncertainty (x)

    % 8. Post-processing
    clearvars -except mode scenario sigma e_crit num_inst fig*
    
    if mode == 1
        fig11 = fig1;
        fig21 = fig2;
    elseif mode == 2
        fig12 = fig1;
        fig22 = fig2;
    end
    
    clear fig1 fig2
end

%% Tile plots together

% 9. Figure 3.1
fig1 = figure;
t1 = tiledlayout(1,2,'TileSpacing','compact');

fig1a = nexttile;
copyobj(allchild(get(fig11,'CurrentAxes')),fig1a)
title('(a)')
xlim([0 90])
ylim([0.005 0.0225])

fig1b = nexttile;
copyobj(allchild(get(fig12,'CurrentAxes')),fig1b)
title('(b)')
xlim([0 90])
ylim([0.005 0.0225])

ylabel(t1, 'Probability density')
xlabel(t1, 'Azimuth (° from due north)')
l1 = legend('','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            'Observed','Perturbed','\epsilon = 15°','\epsilon = 30°',...
            '\epsilon = 45°','\epsilon = 60°','\epsilon = 75°');
l1.Orientation = 'vertical';

fig1.PaperUnits = 'centimeters';
fig1.PaperPosition = [0 0 24 16];
print(fig1,'output/fig3_1','-dpng','-r500')

% 10. Figure 3.2
fig2 = figure;
t2 = tiledlayout(1,2,'TileSpacing','compact');

fig2a = nexttile;
copyobj(allchild(get(fig21,'CurrentAxes')),fig2a)
title('(a)')
xlim([0 90])
ylim([0 30])
set(gca,'Ydir','reverse')

fig2b = nexttile;
copyobj(allchild(get(fig22,'CurrentAxes')),fig2b)
title('(b)')
xlim([0 90])
ylim([0 30])
set(gca,'Ydir','reverse')

ylabel(t2, 'Mismatch (reduced \chi^2 statistic)')
xlabel(t2, 'Obliquity (°)')

l2 = legend('','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            '','','','','','','','','','','','','','','','','','','','',...
            'Observed','Perturbed');
l2.Orientation = 'vertical';

fig2.PaperUnits = 'centimeters';
fig2.PaperPosition = [0 0 24 16];
print(fig2,'output/fig3_2','-dpng','-r500')